// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: employee_to_salary_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSalaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId   int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	SalaryAmount int32  `protobuf:"varint,2,opt,name=salary_amount,json=salaryAmount,proto3" json:"salary_amount,omitempty"`
	Project      string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JoiningDate  string `protobuf:"bytes,4,opt,name=joining_date,json=joiningDate,proto3" json:"joining_date,omitempty"`
}

func (x *CreateSalaryRequest) Reset() {
	*x = CreateSalaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSalaryRequest) ProtoMessage() {}

func (x *CreateSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSalaryRequest.ProtoReflect.Descriptor instead.
func (*CreateSalaryRequest) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSalaryRequest) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateSalaryRequest) GetSalaryAmount() int32 {
	if x != nil {
		return x.SalaryAmount
	}
	return 0
}

func (x *CreateSalaryRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateSalaryRequest) GetJoiningDate() string {
	if x != nil {
		return x.JoiningDate
	}
	return ""
}

type CreateSalaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateSalaryResponse) Reset() {
	*x = CreateSalaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSalaryResponse) ProtoMessage() {}

func (x *CreateSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSalaryResponse.ProtoReflect.Descriptor instead.
func (*CreateSalaryResponse) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSalaryResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateSalaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllSalaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllSalaryRequest) Reset() {
	*x = GetAllSalaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSalaryRequest) ProtoMessage() {}

func (x *GetAllSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSalaryRequest.ProtoReflect.Descriptor instead.
func (*GetAllSalaryRequest) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{2}
}

type GetAllSalaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salaries []*EmployeeSalary `protobuf:"bytes,1,rep,name=salaries,proto3" json:"salaries,omitempty"`
}

func (x *GetAllSalaryResponse) Reset() {
	*x = GetAllSalaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSalaryResponse) ProtoMessage() {}

func (x *GetAllSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSalaryResponse.ProtoReflect.Descriptor instead.
func (*GetAllSalaryResponse) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllSalaryResponse) GetSalaries() []*EmployeeSalary {
	if x != nil {
		return x.Salaries
	}
	return nil
}

type EmployeeSalary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId   int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	SalaryAmount int32  `protobuf:"varint,2,opt,name=salary_amount,json=salaryAmount,proto3" json:"salary_amount,omitempty"`
	Project      string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JoiningDate  string `protobuf:"bytes,4,opt,name=joining_date,json=joiningDate,proto3" json:"joining_date,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Email        string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmployeeSalary) Reset() {
	*x = EmployeeSalary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeSalary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeSalary) ProtoMessage() {}

func (x *EmployeeSalary) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeSalary.ProtoReflect.Descriptor instead.
func (*EmployeeSalary) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{4}
}

func (x *EmployeeSalary) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *EmployeeSalary) GetSalaryAmount() int32 {
	if x != nil {
		return x.SalaryAmount
	}
	return 0
}

func (x *EmployeeSalary) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *EmployeeSalary) GetJoiningDate() string {
	if x != nil {
		return x.JoiningDate
	}
	return ""
}

func (x *EmployeeSalary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeSalary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateSalaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId   int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	SalaryAmount int32  `protobuf:"varint,2,opt,name=salary_amount,json=salaryAmount,proto3" json:"salary_amount,omitempty"`
	Project      string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JoiningDate  string `protobuf:"bytes,4,opt,name=joining_date,json=joiningDate,proto3" json:"joining_date,omitempty"`
}

func (x *UpdateSalaryRequest) Reset() {
	*x = UpdateSalaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSalaryRequest) ProtoMessage() {}

func (x *UpdateSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSalaryRequest.ProtoReflect.Descriptor instead.
func (*UpdateSalaryRequest) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSalaryRequest) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *UpdateSalaryRequest) GetSalaryAmount() int32 {
	if x != nil {
		return x.SalaryAmount
	}
	return 0
}

func (x *UpdateSalaryRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *UpdateSalaryRequest) GetJoiningDate() string {
	if x != nil {
		return x.JoiningDate
	}
	return ""
}

type UpdateSalaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId   int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	SalaryAmount int32  `protobuf:"varint,2,opt,name=salary_amount,json=salaryAmount,proto3" json:"salary_amount,omitempty"`
	Project      string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JoiningDate  string `protobuf:"bytes,4,opt,name=joining_date,json=joiningDate,proto3" json:"joining_date,omitempty"`
}

func (x *UpdateSalaryResponse) Reset() {
	*x = UpdateSalaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSalaryResponse) ProtoMessage() {}

func (x *UpdateSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSalaryResponse.ProtoReflect.Descriptor instead.
func (*UpdateSalaryResponse) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSalaryResponse) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *UpdateSalaryResponse) GetSalaryAmount() int32 {
	if x != nil {
		return x.SalaryAmount
	}
	return 0
}

func (x *UpdateSalaryResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *UpdateSalaryResponse) GetJoiningDate() string {
	if x != nil {
		return x.JoiningDate
	}
	return ""
}

type DeleteSalaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId   int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	SalaryAmount int32  `protobuf:"varint,2,opt,name=salary_amount,json=salaryAmount,proto3" json:"salary_amount,omitempty"`
	Project      string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JoiningDate  string `protobuf:"bytes,4,opt,name=joining_date,json=joiningDate,proto3" json:"joining_date,omitempty"`
}

func (x *DeleteSalaryRequest) Reset() {
	*x = DeleteSalaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSalaryRequest) ProtoMessage() {}

func (x *DeleteSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSalaryRequest.ProtoReflect.Descriptor instead.
func (*DeleteSalaryRequest) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSalaryRequest) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *DeleteSalaryRequest) GetSalaryAmount() int32 {
	if x != nil {
		return x.SalaryAmount
	}
	return 0
}

func (x *DeleteSalaryRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeleteSalaryRequest) GetJoiningDate() string {
	if x != nil {
		return x.JoiningDate
	}
	return ""
}

type DeleteSalaryResposne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteSalaryResposne) Reset() {
	*x = DeleteSalaryResposne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_to_salary_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSalaryResposne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSalaryResposne) ProtoMessage() {}

func (x *DeleteSalaryResposne) ProtoReflect() protoreflect.Message {
	mi := &file_employee_to_salary_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSalaryResposne.ProtoReflect.Descriptor instead.
func (*DeleteSalaryResposne) Descriptor() ([]byte, []int) {
	return file_employee_to_salary_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSalaryResposne) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteSalaryResposne) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_employee_to_salary_service_proto protoreflect.FileDescriptor

var file_employee_to_salary_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x44, 0x61, 0x74, 0x65, 0x22, 0x48, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x15,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53,
	0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x08, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x08, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x69, 0x65, 0x73,
	0x22, 0xbd, 0x01, 0x0a, 0x0e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x22, 0x98, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x48, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xbe, 0x02, 0x0a,
	0x10, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x54, 0x6f, 0x53, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x12, 0x49, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x6c,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a,
	0x22, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x52, 0x4f,
	0x4a, 0x45, 0x43, 0x54, 0x5f, 0x31, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_employee_to_salary_service_proto_rawDescOnce sync.Once
	file_employee_to_salary_service_proto_rawDescData = file_employee_to_salary_service_proto_rawDesc
)

func file_employee_to_salary_service_proto_rawDescGZIP() []byte {
	file_employee_to_salary_service_proto_rawDescOnce.Do(func() {
		file_employee_to_salary_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_employee_to_salary_service_proto_rawDescData)
	})
	return file_employee_to_salary_service_proto_rawDescData
}

var file_employee_to_salary_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_employee_to_salary_service_proto_goTypes = []any{
	(*CreateSalaryRequest)(nil),  // 0: proto.CreateSalaryRequest
	(*CreateSalaryResponse)(nil), // 1: proto.CreateSalaryResponse
	(*GetAllSalaryRequest)(nil),  // 2: proto.GetAllSalaryRequest
	(*GetAllSalaryResponse)(nil), // 3: proto.GetAllSalaryResponse
	(*EmployeeSalary)(nil),       // 4: proto.EmployeeSalary
	(*UpdateSalaryRequest)(nil),  // 5: proto.UpdateSalaryRequest
	(*UpdateSalaryResponse)(nil), // 6: proto.UpdateSalaryResponse
	(*DeleteSalaryRequest)(nil),  // 7: proto.DeleteSalaryRequest
	(*DeleteSalaryResposne)(nil), // 8: proto.DeleteSalaryResposne
}
var file_employee_to_salary_service_proto_depIdxs = []int32{
	4, // 0: proto.GetAllSalaryResponse.salaries:type_name -> proto.EmployeeSalary
	0, // 1: proto.EmployeeToSalary.CreateSalary:input_type -> proto.CreateSalaryRequest
	2, // 2: proto.EmployeeToSalary.GetAllSalary:input_type -> proto.GetAllSalaryRequest
	5, // 3: proto.EmployeeToSalary.UpdateSalary:input_type -> proto.UpdateSalaryRequest
	7, // 4: proto.EmployeeToSalary.DeleteSalary:input_type -> proto.DeleteSalaryRequest
	1, // 5: proto.EmployeeToSalary.CreateSalary:output_type -> proto.CreateSalaryResponse
	3, // 6: proto.EmployeeToSalary.GetAllSalary:output_type -> proto.GetAllSalaryResponse
	6, // 7: proto.EmployeeToSalary.UpdateSalary:output_type -> proto.UpdateSalaryResponse
	8, // 8: proto.EmployeeToSalary.DeleteSalary:output_type -> proto.DeleteSalaryResposne
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_employee_to_salary_service_proto_init() }
func file_employee_to_salary_service_proto_init() {
	if File_employee_to_salary_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_employee_to_salary_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSalaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSalaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllSalaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllSalaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EmployeeSalary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateSalaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateSalaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSalaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_to_salary_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSalaryResposne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_employee_to_salary_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_to_salary_service_proto_goTypes,
		DependencyIndexes: file_employee_to_salary_service_proto_depIdxs,
		MessageInfos:      file_employee_to_salary_service_proto_msgTypes,
	}.Build()
	File_employee_to_salary_service_proto = out.File
	file_employee_to_salary_service_proto_rawDesc = nil
	file_employee_to_salary_service_proto_goTypes = nil
	file_employee_to_salary_service_proto_depIdxs = nil
}
